# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Witek/huffmann/proba4/proba4.cache/wt [current_project]
set_property parent.project_path C:/Witek/huffmann/proba4/proba4.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths {
  c:/Witek/huffmann/ip_repo/myip2_1.0
  c:/Witek/huffmann/ip_repo/myip_1.0
  c:/Witek/huffmann/ip_repo/coder_1.0
} [current_project]
set_property ip_output_repo c:/Witek/huffmann/proba4/proba4.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/Witek/huffmann/proba4/proba4.srcs/sources_1/bd/cotex_design/hdl/cotex_design_wrapper.v
add_files C:/Witek/huffmann/proba4/proba4.srcs/sources_1/bd/cotex_design/cotex_design.bd
set_property used_in_implementation false [get_files -all c:/Witek/huffmann/proba4/proba4.srcs/sources_1/bd/cotex_design/ip/cotex_design_processing_system7_0_0/cotex_design_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Witek/huffmann/proba4/proba4.srcs/sources_1/bd/cotex_design/ip/cotex_design_rst_ps7_0_100M_0/cotex_design_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Witek/huffmann/proba4/proba4.srcs/sources_1/bd/cotex_design/ip/cotex_design_rst_ps7_0_100M_0/cotex_design_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Witek/huffmann/proba4/proba4.srcs/sources_1/bd/cotex_design/ip/cotex_design_rst_ps7_0_100M_0/cotex_design_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Witek/huffmann/proba4/proba4.srcs/sources_1/bd/cotex_design/ip/cotex_design_auto_pc_0/cotex_design_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Witek/huffmann/proba4/proba4.srcs/sources_1/bd/cotex_design/cotex_design_ooc.xdc]
set_property is_locked true [get_files C:/Witek/huffmann/proba4/proba4.srcs/sources_1/bd/cotex_design/cotex_design.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top cotex_design_wrapper -part xc7z020clg484-1


write_checkpoint -force -noxdef cotex_design_wrapper.dcp

catch { report_utilization -file cotex_design_wrapper_utilization_synth.rpt -pb cotex_design_wrapper_utilization_synth.pb }
