# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/cotex_design/cotex_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cotex_design || ORIG_REF_NAME==cotex_design}]

# IP: bd/cotex_design/ip/cotex_design_processing_system7_0_0/cotex_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cotex_design_processing_system7_0_0 || ORIG_REF_NAME==cotex_design_processing_system7_0_0}]

# IP: bd/cotex_design/ip/cotex_design_ps7_0_axi_periph_0/cotex_design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cotex_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==cotex_design_ps7_0_axi_periph_0}]

# IP: bd/cotex_design/ip/cotex_design_rst_ps7_0_100M_0/cotex_design_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cotex_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==cotex_design_rst_ps7_0_100M_0}]

# IP: bd/cotex_design/ip/cotex_design_myip2_0_0/cotex_design_myip2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cotex_design_myip2_0_0 || ORIG_REF_NAME==cotex_design_myip2_0_0}]

# IP: bd/cotex_design/ip/cotex_design_auto_pc_0/cotex_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cotex_design_auto_pc_0 || ORIG_REF_NAME==cotex_design_auto_pc_0}]

# XDC: bd/cotex_design/ip/cotex_design_processing_system7_0_0/cotex_design_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cotex_design_processing_system7_0_0 || ORIG_REF_NAME==cotex_design_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/cotex_design/ip/cotex_design_rst_ps7_0_100M_0/cotex_design_rst_ps7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cotex_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==cotex_design_rst_ps7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/cotex_design/ip/cotex_design_rst_ps7_0_100M_0/cotex_design_rst_ps7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cotex_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==cotex_design_rst_ps7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/cotex_design/ip/cotex_design_rst_ps7_0_100M_0/cotex_design_rst_ps7_0_100M_0_ooc.xdc

# XDC: bd/cotex_design/ip/cotex_design_auto_pc_0/cotex_design_auto_pc_0_ooc.xdc

# XDC: bd/cotex_design/cotex_design_ooc.xdc
